/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'SF Mono', 'monospace'],
      },
      colors: {
        background: {
          base: '#F8F7F7',
          weak: '#F0EFED',
          strong: '#FFFFFF',
          overlay: '#FFFFFF',
        },
        surface: {
          'raised-base': '#FFFFFF',
          'raised-hover': '#F5F4F2',
          'raised-active': '#EBE9E6',
          'caution-base': '#FFFBEB',
          'caution-weak': '#FEF9C3',
          'caution-strong': '#FDE047',
          'success-base': '#F0FDF4',
          'success-weak': '#DCFCE7',
          'success-strong': '#86EFAC',
          'error-base': '#FEF2F2',
          'error-weak': '#FEE2E2',
          'error-strong': '#FCA5A5',
          'information-base': '#EFF6FF',
          'information-weak': '#DBEAFE',
          'information-strong': '#93C5FD',
        },
        border: {
          'weak-base': '#E5E3E0',
          'weak-hover': '#D6D3CD',
          'weak-active': '#A8A29E',
          'weak-strong': '#78716C',
          'strong-base': '#A8A29E',
          'strong-hover': '#78716C',
          'strong-active': '#57534E',
          'strong-strong': '#44403C',
          'caution-base': '#FCD34D',
          'success-base': '#4ADE80',
          'error-base': '#F87171',
          'information-base': '#60A5FA',
          'highlight-base': '#000000',
        },
        text: {
          strong: '#1C1917',
          base: '#44403C',
          subtle: '#78716C',
          weak: '#A8A29E',
          disabled: '#D6D3CD',
          'caution-strong': '#A16207',
          'success-strong': '#15803D',
          'error-strong': '#B91C1C',
          'information-strong': '#1D4ED8',
          white: '#FFFFFF',
          black: '#000000',
          'interactive-base': '#2563EB',
          'interactive-hover': '#1D4ED8',
          'interactive-active': '#1E40AF',
          'interactive-weak': '#93C5FD',
          'interactive-strong': '#1E3A8A',
          'interactive-subtle': '#DBEAFE',
        },
        icon: {
          strong: '#44403C',
          base: '#78716C',
          subtle: '#A8A29E',
          weak: '#D6D3CD',
          disabled: '#E5E3E0',
          'caution-strong': '#A16207',
          'success-strong': '#15803D',
          'error-strong': '#B91C1C',
          'information-strong': '#1D4ED8',
          white: '#FFFFFF',
          black: '#000000',
          'interactive-base': '#2563EB',
          'interactive-hover': '#1D4ED8',
          'interactive-active': '#1E40AF',
          'interactive-weak': '#93C5FD',
          'interactive-strong': '#1E3A8A',
        },
        fill: {
          strong: '#1C1917',
          base: '#44403C',
          subtle: '#78716C',
          weak: '#A8A29E',
          weakest: '#D6D3CD',
          disabled: '#E5E3E0',
          transparent: 'transparent',
          white: '#FFFFFF',
          black: '#000000',
          blue: '#2563EB',
        },
        status: {
          error: '#DC2626',
          success: '#16A34A',
          warning: '#CA8A04',
          information: '#2563EB',
          neutral: '#6B7280',
          active: '#2563EB',
          inactive: '#9CA3AF',
          pending: '#CA8A04',
        },
      },
      fontSize: {
        '12-regular': ['0.75rem', { lineHeight: '1rem' }],
        '14-medium': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '500' }],
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      },
      borderRadius: {
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
